baseURL = "https://blog.zjyl1994.com/"
languageCode = "zh-CN"
defaultContentLanguage = "zh"
title = "咸鱼的小鱼塘"
enableRobotsTXT = true
enableEmoji = true
theme = "PaperMod"

hasCJKLanguage = true
[pagination]
  pagerSize = 5
copyright = "<a rel=\"license noopener\" href=\"https://creativecommons.org/licenses/by-nc-sa/4.0/\" target=\"_blank\">CC BY-NC-SA 4.0</a>"

ignoreLogs = ['warning-goldmark-raw-html']

[outputs]
  home = ["HTML", "RSS", "JSON"]

[services]
  [services.googleAnalytics]
    ID = "UA-109257164-2"
  [services.disqus]
    shortname = "zjyl1994-no-zi-liu-di"

[sitemap]       
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]         
  name = "个人主页"
  weight = 5
  identifier = "index"
  url = "https://www.zjyl1994.com"
[[menu.main]]         
  name = "博客首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 15
  identifier = "archives"
  url = "/archives/"
[[menu.main]]
  name = "标签"
  weight = 20
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "分类"
  weight = 25
  identifier = "categories"
  url = "/categories/"

[params]
  debug = false
  since = "2016"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false
  DateFormat = "2006-01-02"
  ShowRssButtonInSectionTermList = true
  disableSpecial1stPost = false
  author = "zjyl1994"

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
